package clientAppSide;

import java.util.ArrayList;

import javax.swing.JOptionPane;

public class FacultyAssignedCoursesUI extends javax.swing.JDialog
{
    private static String operation, selection;
    private static ArrayList<String> dataList;
  
    public FacultyAssignedCoursesUI() {
        initComponents();
    }

    @SuppressWarnings("unchecked")
    private void initComponents() {

        /*****************************************************************************************************************/

        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(true);
        
        jList1.setModel(new javax.swing.AbstractListModel<String>()
        {
            public int getSize() { return dataList.size(); }
            public String getElementAt(int i) { return dataList.get(i); }
        });
        
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("My Assigned Courses");
        jScrollPane1.setViewportView(jList1);

        /*****************************************************************************************************************/

        jButton1.setText("Post Grades");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
            	if(jList1.isSelectionEmpty())
            	{
            		JOptionPane.showMessageDialog(null, "No selections made!", "Info", JOptionPane.ERROR_MESSAGE);
            	}
            	else
            	{
            		String operationName = "getEnrolledStudents";
                	String requestingUI = "displayEnrolledStudents";
                	
                	ArrayList<String> serverInfo = new ArrayList<String>();
                	
                	serverInfo.add(operationName);
                	serverInfo.add(requestingUI);
                	serverInfo.add(jList1.getSelectedValue().substring(12));
                	
                	//System.out.println(serverInfo);
                    ClientConsole.accept(serverInfo);
            	}
            }
        });

        /*****************************************************************************************************************/

        jButton2.setText("View Enrolled Students");
        jButton2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
            	if(jList1.isSelectionEmpty())
            	{
            		JOptionPane.showMessageDialog(null, "No selections made!", "Info", JOptionPane.ERROR_MESSAGE);
            	}
            	else
            	{
            		String operationName = "getEnrolledStudents";
                	String requestingUI = "displayUsersList";
                	
                	ArrayList<String> serverInfo = new ArrayList<String>();
                	
                	serverInfo.add(operationName);
                	serverInfo.add(requestingUI);
                	serverInfo.add(jList1.getSelectedValue().substring(12));
                	
                    ClientConsole.accept(serverInfo);
            	}
            }
        });

        jButton3.setText("Update Grades");
        jButton3.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
            	if(jList1.isSelectionEmpty())
            	{
            		JOptionPane.showMessageDialog(null, "No selections made!", "Info", JOptionPane.ERROR_MESSAGE);
            	}
            	else
            	{
            		String operationName = "viewCourseGrades";
                	String requestingUI = "displayCourseGrades";
                	
                	ArrayList<String> serverInfo = new ArrayList<String>();
                	
                	serverInfo.add(operationName);
                	serverInfo.add(requestingUI);
                	serverInfo.add(jList1.getSelectedValue().substring(12));
                	
                	//System.out.println(serverInfo);
                    ClientConsole.accept(serverInfo);
            	}
            }
        });
        
        /*****************************************************************************************************************/
        //This section is auto generated by java swing Net-beans

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
        );

        pack();
    }
    
    /*****************************************************************************************************************/

    public static void displayObjectsList(ArrayList<String> list)
    {
    	operation = list.get(0);
    	selection = list.get(2);
    	
    	list.subList(0, 3).clear();
    	
    	dataList = list;
    	
    	FacultyAssignedCoursesUI.display();
    }
    
    /*****************************************************************************************************************/
    //This section is auto generated by java swing Net-beans

    public static void display() 
    {
        try {for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {javax.swing.UIManager.setLookAndFeel(info.getClassName());break;}}} 
        catch (ClassNotFoundException ex) {java.util.logging.Logger.getLogger(FacultyAssignedCoursesUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);}
        catch (InstantiationException ex) {java.util.logging.Logger.getLogger(FacultyAssignedCoursesUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);}
        catch (IllegalAccessException ex) {java.util.logging.Logger.getLogger(FacultyAssignedCoursesUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);}
        catch (javax.swing.UnsupportedLookAndFeelException ex) {java.util.logging.Logger.getLogger(FacultyAssignedCoursesUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);}
        java.awt.EventQueue.invokeLater(new Runnable() {public void run() {new FacultyAssignedCoursesUI().setVisible(true);}});
    }

    /*****************************************************************************************************************/
    //This section is auto generated by java swing Net-beans

    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private static javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    
    /*****************************************************************************************************************/
}
