/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clientAppSide;

import java.util.ArrayList;

import javax.swing.JOptionPane;

/**
 *
 * @author susha
 */
public class FacultyUpdateGradesUI extends javax.swing.JDialog
{
	private static ArrayList<String> gradedEntries = new ArrayList<String>();
	private static String selection, entry;
    /**
     * Creates new form FacultyUpdateGradesUI
     */
    public FacultyUpdateGradesUI()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() 
    {

        jRadioButton1 = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(true);
        
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Graded Students");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Post Grades");

        jList1.setModel(new javax.swing.AbstractListModel<String>()
    	{
            public int getSize() 
            { 
            	return gradedEntries.size(); 
            }
            public String getElementAt(int i) 
            { 
            	return gradedEntries.get(i); 
            }
        });
        
        jScrollPane1.setViewportView(jList1);

        jButton3.setText("Update Grades");
        jButton3.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
            	if(jList1.isSelectionEmpty())
            	{
            		JOptionPane.showMessageDialog(null, "No Student Selected!", "Info", JOptionPane.ERROR_MESSAGE);
            	}
            	else
            	{
            		String[] options = {"Remove Grade", "A", "B", "C", "D", "E", "F"};
                    String grade = (String) JOptionPane.showInputDialog(null, jList1.getSelectedValue(), "Select Student Grade", JOptionPane.YES_NO_CANCEL_OPTION, null, options, options[0]);

                    if (grade != null)
                    {
                    	if(grade.equals("Remove Grade"))
                        {
                        	gradedEntries.remove(jList1.getSelectedValue().toString());
                        	displayGradedList();
                        	return;
                        }
                    	else
                    	{
                    		String student = jList1.getSelectedValue().substring(0, jList1.getSelectedValue().length() - 4);
                        	entry = student + " - " + grade;
                        	gradedEntries.remove(jList1.getSelectedValue());
                        	gradedEntries.add(entry);
                        	displayGradedList();
                            return;
                    	}
                    }
            	}
            }
        });

        jButton4.setText("Submit");
        jButton4.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
            	if(gradedEntries.isEmpty())
            	{
            		JOptionPane.showMessageDialog(null, "No Grades Entered Yet!", "Info", JOptionPane.ERROR_MESSAGE);
            	}
            	else
            	{
            		String operationName = "postGrades";
                	String courseName = selection;
                	ArrayList<String> serverInfo = new ArrayList<String>();
                	
                	serverInfo.add(operationName);
                	serverInfo.add(courseName);
                	
                	for(int i=0; i<gradedEntries.size(); i++)
                	{
                		serverInfo.add(gradedEntries.get(i).substring(gradedEntries.get(i).length() - 10));
                	}
         	
                	//System.out.println(serverInfo);
                	ClientConsole.accept(serverInfo);
            	}
            }
        });

        jButton2.setText("View Student");
        jButton2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
            	if(jList1.isSelectionEmpty())
            	{
            		JOptionPane.showMessageDialog(null, "No Selections Made!", "Info", JOptionPane.ERROR_MESSAGE);
            	}
            	else
            	{
            		String operationName = "viewUserProfile";
                	String requestingUI = "studentUserViewProfile";
                	
                	String memberid = jList1.getSelectedValue().substring(0, jList1.getSelectedValue().length() - 4);
                	String studentid = memberid.substring(memberid.length() - 6);
                	
                	ArrayList<String> serverInfo = new ArrayList<String>();
                	
                	serverInfo.add(operationName);
                	serverInfo.add(requestingUI);
                	serverInfo.add(studentid);
                    ClientConsole.accept(serverInfo);
            	}
            }
        });

        

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static void displayGradedList()
    {
    	jList1.setModel(new javax.swing.AbstractListModel<String>() 
    	{
            public int getSize() 
            { 
            	return gradedEntries.size(); 
            }
            
            public String getElementAt(int i) 
            { 
            	return gradedEntries.get(i);
            }
        });
    }
    
    public static void displayCourseGrades(ArrayList<String> list)
    {
    	selection = list.get(2);
    	
    	list.subList(0, 3).clear();
    	
    	gradedEntries = list;
    	
    	display();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void display() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FacultyUpdateGradesUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FacultyUpdateGradesUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FacultyUpdateGradesUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FacultyUpdateGradesUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FacultyUpdateGradesUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private static javax.swing.JList<String> jList1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}