package clientAppSide;
import java.util.ArrayList;
import javax.swing.JOptionPane;

public class ViewCourseSchedulesUI extends javax.swing.JDialog
{
	private static ArrayList<String> courseSchedules;
	private static String passedSelection;
	
    public ViewCourseSchedulesUI()
    {
        initComponents();
    }

    /***********************************************************************************************************/

    private void initComponents()
    {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(true);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(passedSelection + " - Weekly Schedules");

        jList1.setModel(new javax.swing.AbstractListModel<String>()
        {
            public int getSize() { return courseSchedules.size(); }
            public String getElementAt(int i) { return courseSchedules.get(i); }
        });
        
        jScrollPane1.setViewportView(jList1);
        
        /***********************************************************************************************************/

        jButton1.setText("Edit Schedule");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
            	if(jList1.isSelectionEmpty())
            	{
            		JOptionPane.showMessageDialog(null, "No Selections Made!", "Server Feedback", JOptionPane.INFORMATION_MESSAGE);
            	}
            	else
            	{
            		
            	}
            }
        });
        
        if(ClientUserInfo.user.getUserType().equals("studentmember") 
        	|| ClientUserInfo.user.getUserType().equals("publicuser")
        	|| ClientUserInfo.user.getUserType().equals("facultyInstructor") 
        	|| ClientUserInfo.user.getUserType().equals("facultyChair")
        	|| ClientUserInfo.user.getUserType().equals("noRoleFaculty"))
        {
        	jButton1.setVisible(false);
        }

        /***********************************************************************************************************/
        //This section is auto generated by java swing Net-beans

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(8, 8, 8))
        );

        pack();
    }

    /***********************************************************************************************************/

    public static void displaySchedulesList(ArrayList<String> schedules)
    {
    	passedSelection = schedules.get(2);
    	schedules.subList(0, 3).clear();
    	courseSchedules = schedules;
    	ViewCourseSchedulesUI.display();
    }
    
    /***********************************************************************************************************/
    //This section is auto generated by java swing Net-beans

    public static void display()
    {
        try {for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())){javax.swing.UIManager.setLookAndFeel(info.getClassName());break;}}}
        catch (ClassNotFoundException ex) {java.util.logging.Logger.getLogger(ViewCourseSchedulesUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);}
        catch (InstantiationException ex) {java.util.logging.Logger.getLogger(ViewCourseSchedulesUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);}
        catch (IllegalAccessException ex) {java.util.logging.Logger.getLogger(ViewCourseSchedulesUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);}
        catch (javax.swing.UnsupportedLookAndFeelException ex) {java.util.logging.Logger.getLogger(ViewCourseSchedulesUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);}
        java.awt.EventQueue.invokeLater(new Runnable(){public void run(){new ViewCourseSchedulesUI().setVisible(true);}});
    }

    /***********************************************************************************************************/
    //This section is auto generated by java swing Net-beans

    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;

    /***********************************************************************************************************/

}